### PR TITLE
add ReverseRegistration event

### PR DESCRIPTION
**Pull request by scottrepreneur**

### CODE REVIEW

**Comment by hongnhut199** [comment]
QmaibP61e3a4r6Bp895FQFB6ohqt5gMK4yeNy6yXxBmi8N

**Review by Arachnid — COMMENTED** [review]
Thanks for this! If we're adding support for reverse names, though, we should cover all the cases - can you add handlers for claim/claimWithResolver too?

**Comment by holic** [comment]
I'm interested in reviving this PR so that it can be merged.

@Arachnid Can you share more about what info you're looking to index in the `claim` and `claimWithResolver` calls? Is there something missing here for compatibility purposes?

**Review by Vladisvob — APPROVED** [review]
#49

**Comment by Arachnid** [comment]
The new reverse registrar, currently deployed on testnets, will support emitting the appropriate events - so we will need to write support for that rather than doing transaction tracing like this.

**Comment by Dizotoff** [comment]
Hi @Arachnid 

Is there a way to determine the primary ENS name by wallet address at the moment?

**Pull request closed without merging**
